<?php

namespace AppBundle\Repository;

/**
 * AgeCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgeCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
