<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishListsRepository extends \Doctrine\ORM\EntityRepository
{

	 public function findPlanById($id)
    {
        $qb = $this->createQueryBuilder('plan')
        ->where('plan.goals = :id')
        ->setParameter('id', $id)
        ->getQuery()
        ->getResult();

        return $qb;
    }

}