<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishListsRepository extends \Doctrine\ORM\EntityRepository
{

    public function findPlanById($id)
    {
        $qb = $this->createQueryBuilder('plan')
            ->Where('plan.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();

        return $qb;
    }

    public function findPlanByCalories($result)
    {
        return $this->createQueryBuilder('plans')
            ->andWhere('plans.caloriesNum >= :result')
            ->setParameter('result', $result)
            ->getQuery()
            ->getResult();
    }

}