<?php

namespace AppBundle\Repository;

/**
 * ExercisesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExercisesRepository extends \Doctrine\ORM\EntityRepository
{
}
