# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.current_user_service:
        class: AppBundle\Service\CurrentUserService
        arguments:
            - '@security.token_storage'

    app.calorie_calculator_service:
        class: AppBundle\Service\CalorieCalculatorService
        arguments:
            - '@session'

    app.product_dislike_service:
            class: AppBundle\Service\ProductDislikeService
            arguments:
            - '@session'



